RecipesTable:
  Type: AWS::DynamoDB::Table
  Properties:
    TableName: recipes-table-${self:provider.stage}
    BillingMode: PAY_PER_REQUEST
    AttributeDefinitions:
      - AttributeName: id
        AttributeType: S
      - AttributeName: title
        AttributeType: S
    KeySchema:
      - AttributeName: id
        KeyType: HASH
    GlobalSecondaryIndexes:
      - IndexName: titleIndex
        KeySchema:
          - AttributeName: title
            KeyType: HASH
        Projection:
          ProjectionType: ALL