RecipesTable:
  Type: AWS::DynamoDB::Table
  Properties:
    TableName: recipe-table-${self:provider.stage}
    BillingMode: PAY_PER_REQUEST
    AttributeDefinitions:
      - AttributeName: id
        AttributeType: S
      - AttributeName: type
        AttributeType: S
    KeySchema:
      - AttributeName: id
        KeyType: HASH
    GlobalSecondaryIndexes:
      - IndexName: typeIndex
        KeySchema:
          - AttributeName: type
            KeyType: HASH
        Projection:
          ProjectionType: ALL
